# Pandas Libraray

In [4]:
import pandas as pd

In [5]:
bk = pd.read_csv(r'C:\Users\HP\OneDrive\Desktop\book.csv')

In [19]:
bk.head()

,Gender,Age,Occupation,Annual Income,Needle Stick Injuries,Knowledge and Training on Needle Stick Injury Prevention,Availability of Safety Equipment,Adherence to Safety Protocols,Work Environment Factors
0,2,2,2,3,4.25,4.75,4.0,4.00,4.75
1,1,3,1,5,3.75,4.00,4.0,3.75,3.75
2,2,1,1,5,4.00,4.00,4.0,4.00,4.00
3,2,2,1,4,4.25,3.75,4.0,4.25,4.00
4,1,2,1,5,4.75,2.75,4.0,4.00,4.25

In [20]:
bk.tail()

,Gender,Age,Occupation,Annual Income,Needle Stick Injuries,Knowledge and Training on Needle Stick Injury Prevention,Availability of Safety Equipment,Adherence to Safety Protocols,Work Environment Factors
95,1,2,1,5,2.0,4.5,4.25,2.75,3.50
96,1,3,2,4,4.0,4.0,4.00,4.25,4.00
97,1,2,2,5,5.0,4.0,4.25,4.50,4.75
98,2,1,2,3,3.0,3.0,3.00,3.00,3.00
99,2,2,2,5,5.0,5.0,5.00,5.00,5.00

In [21]:
bk.shape

(100, 9)

In [22]:
bk.describe()

,Gender,Age,Occupation,Annual Income,Needle Stick Injuries,Knowledge and Training on Needle Stick Injury Prevention,Availability of Safety Equipment,Adherence to Safety Protocols,Work Environment Factors
count,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000
mean,1.540000,2.190000,1.680000,3.720000,3.755000,3.660000,3.657500,3.722500,3.747500
std,0.500908,0.906709,0.566399,1.247867,1.155236,1.130679,1.120659,1.146412,1.146192
min,1.000000,1.000000,1.000000,1.000000,1.000000,0.500000,0.500000,1.000000,0.500000
25%,1.000000,2.000000,1.000000,3.000000,3.375000,3.000000,3.250000,3.250000,3.500000
50%,2.000000,2.000000,2.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000
75%,2.000000,3.000000,2.000000,5.000000,4.500000,4.312500,4.500000,4.500000,4.500000
max,2.000000,5.000000,3.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000

In [23]:
bk.iloc[5:11,0:4]

    Gender  Age  Occupation  Annual Income
5        1    3           2              5
6        1    2           2              5
7        2    1           2              4
8        2    2           2              5
9        2    2           1              3
10       2    2           1              4

In [25]:
bk.loc[0:10,("Annual Income", "Occupation")]

    Annual Income  Occupation
0               3           2
1               5           1
2               5           1
3               4           1
4               5           1
5               5           2
6               5           2
7               4           2
8               5           2
9               3           1
10              4           1

In [26]:
bk.loc[11:20,("Needle Stick Injuries","Occupation","Annual Income")]

    Needle Stick Injuries  Occupation  Annual Income
11                   4.75           1              4
12                   1.75           1              2
13                   4.00           1              3
14                   4.50           1              4
15                   5.00           2              5
16                   3.75           2              5
17                   1.00           2              1
18                   4.00           2              4
19                   1.75           2              1
20                   4.50           2              4

In [32]:
bk.drop(["Annual Income","Adherence to Safety Protocols","Availability of Safety Equipment","Knowledge and Training on Needle Stick Injury Prevention"],axis=1)

    Gender  Age  Occupation  Needle Stick Injuries  Work Environment Factors
0        2    2           2                   4.25                      4.75
1        1    3           1                   3.75                      3.75
2        2    1           1                   4.00                      4.00
3        2    2           1                   4.25                      4.00
4        1    2           1                   4.75                      4.25
..     ...  ...         ...                    ...                       ...
95       1    2           1                   2.00                      3.50
96       1    3           2                   4.00                      4.00
97       1    2           2                   5.00                      4.75
98       2    1           2                   3.00                      3.00
99       2    2           2                   5.00                      5.00

[100 rows x 5 columns]

In [33]:
bk.drop("Knowledge and Training on Needle Stick Injury Prevention",axis=1)

,Gender,Age,Occupation,Annual Income,Needle Stick Injuries,Availability of Safety Equipment,Adherence to Safety Protocols,Work Environment Factors
0,2,2,2,3,4.25,4.00,4.00,4.75
1,1,3,1,5,3.75,4.00,3.75,3.75
2,2,1,1,5,4.00,4.00,4.00,4.00
3,2,2,1,4,4.25,4.00,4.25,4.00
4,1,2,1,5,4.75,4.00,4.00,4.25
...,...,...,...,...,...,...,...,...
95,1,2,1,5,2.00,4.25,2.75,3.50
96,1,3,2,4,4.00,4.00,4.25,4.00
97,1,2,2,5,5.00,4.25,4.50,4.75
98,2,1,2,3,3.00,3.00,3.00,3.00
99,2,2,2,5,5.00,5.00,5.00,5.00

In [34]:
bk.drop([10,11,12,13,14,15],axis = 0)

,Gender,Age,Occupation,Annual Income,Needle Stick Injuries,Knowledge and Training on Needle Stick Injury Prevention,Availability of Safety Equipment,Adherence to Safety Protocols,Work Environment Factors
0,2,2,2,3,4.25,4.75,4.00,4.00,4.75
1,1,3,1,5,3.75,4.00,4.00,3.75,3.75
2,2,1,1,5,4.00,4.00,4.00,4.00,4.00
3,2,2,1,4,4.25,3.75,4.00,4.25,4.00
4,1,2,1,5,4.75,2.75,4.00,4.00,4.25
...,...,...,...,...,...,...,...,...,...
95,1,2,1,5,2.00,4.50,4.25,2.75,3.50
96,1,3,2,4,4.00,4.00,4.00,4.25,4.00
97,1,2,2,5,5.00,4.00,4.25,4.50,4.75
98,2,1,2,3,3.00,3.00,3.00,3.00,3.00
99,2,2,2,5,5.00,5.00,5.00,5.00,5.00

In [36]:
bk.head(20)

,Gender,Age,Occupation,Annual Income,Needle Stick Injuries,Knowledge and Training on Needle Stick Injury Prevention,Availability of Safety Equipment,Adherence to Safety Protocols,Work Environment Factors
0,2,2,2,3,4.25,4.75,4.00,4.00,4.75
1,1,3,1,5,3.75,4.00,4.00,3.75,3.75
2,2,1,1,5,4.00,4.00,4.00,4.00,4.00
3,2,2,1,4,4.25,3.75,4.00,4.25,4.00
4,1,2,1,5,4.75,2.75,4.00,4.00,4.25
5,1,3,2,5,4.25,4.00,4.50,3.75,4.25
6,1,2,2,5,4.00,4.00,4.00,4.25,3.75
7,2,1,2,4,3.00,3.00,3.25,3.75,3.25
8,2,2,2,5,4.25,4.50,4.25,4.75,4.50
9,2,2,1,3,3.00,2.25,2.75,2.50,3.00
10,2,2,1,4,4.50,4.50,4.00,4.75,4.75
11,2,2,1,4,4.75,4.75,4.50,4.75,4.50
12,2,2,1,2,1.75,1.00,1.50,1.25,1.25
13,2,2,1,3,4.00,4.00,4.00,4.00,4.25
14,2,2,1,4,4.50,4.00,4.00,4.00,4.25
15,2,3,2,5,5.00,5.00,5.00,5.00,5.00
16,2,2,2,5,3.75,4.00,4.25,4.00,4.00
17,2,2,2,1,1.00,1.00,1.00,1.00,1.00
18,2,2,2,4,4.00,4.00,4.00,4.00,4.00
19,1,2,2,1,1.75,1.00,1.00,1.00,1.25

In [37]:
df = bk.drop([10,11,12,13,14,15],axis = 0)
df

,Gender,Age,Occupation,Annual Income,Needle Stick Injuries,Knowledge and Training on Needle Stick Injury Prevention,Availability of Safety Equipment,Adherence to Safety Protocols,Work Environment Factors
0,2,2,2,3,4.25,4.75,4.00,4.00,4.75
1,1,3,1,5,3.75,4.00,4.00,3.75,3.75
2,2,1,1,5,4.00,4.00,4.00,4.00,4.00
3,2,2,1,4,4.25,3.75,4.00,4.25,4.00
4,1,2,1,5,4.75,2.75,4.00,4.00,4.25
...,...,...,...,...,...,...,...,...,...
95,1,2,1,5,2.00,4.50,4.25,2.75,3.50
96,1,3,2,4,4.00,4.00,4.00,4.25,4.00
97,1,2,2,5,5.00,4.00,4.25,4.50,4.75
98,2,1,2,3,3.00,3.00,3.00,3.00,3.00
99,2,2,2,5,5.00,5.00,5.00,5.00,5.00

In [38]:
df.head(20)

,Gender,Age,Occupation,Annual Income,Needle Stick Injuries,Knowledge and Training on Needle Stick Injury Prevention,Availability of Safety Equipment,Adherence to Safety Protocols,Work Environment Factors
0,2,2,2,3,4.25,4.75,4.00,4.00,4.75
1,1,3,1,5,3.75,4.00,4.00,3.75,3.75
2,2,1,1,5,4.00,4.00,4.00,4.00,4.00
3,2,2,1,4,4.25,3.75,4.00,4.25,4.00
4,1,2,1,5,4.75,2.75,4.00,4.00,4.25
5,1,3,2,5,4.25,4.00,4.50,3.75,4.25
6,1,2,2,5,4.00,4.00,4.00,4.25,3.75
7,2,1,2,4,3.00,3.00,3.25,3.75,3.25
8,2,2,2,5,4.25,4.50,4.25,4.75,4.50
9,2,2,1,3,3.00,2.25,2.75,2.50,3.00
16,2,2,2,5,3.75,4.00,4.25,4.00,4.00
17,2,2,2,1,1.00,1.00,1.00,1.00,1.00
18,2,2,2,4,4.00,4.00,4.00,4.00,4.00
19,1,2,2,1,1.75,1.00,1.00,1.00,1.25
20,1,1,2,4,4.50,4.00,3.75,4.50,4.50
21,2,2,2,5,5.00,5.00,5.00,5.00,5.00
22,1,2,2,4,3.75,3.25,4.00,3.75,4.25
23,1,2,2,3,4.00,4.25,3.50,3.75,4.25
24,1,2,2,3,4.50,3.00,3.00,4.00,3.50
25,1,2,1,5,4.50,4.25,5.00,4.50,4.25

In [39]:
bk.max()

Gender                                                      2.0
Age                                                         5.0
Occupation                                                  3.0
Annual Income                                               5.0
Needle Stick Injuries                                       5.0
Knowledge and Training on Needle Stick Injury Prevention    5.0
Availability of Safety Equipment                            5.0
Adherence to Safety Protocols                               5.0
Work Environment Factors                                    5.0
dtype: float64

In [40]:
bk.min()

Gender                                                      1.0
Age                                                         1.0
Occupation                                                  1.0
Annual Income                                               1.0
Needle Stick Injuries                                       1.0
Knowledge and Training on Needle Stick Injury Prevention    0.5
Availability of Safety Equipment                            0.5
Adherence to Safety Protocols                               1.0
Work Environment Factors                                    0.5
dtype: float64

In [41]:
bk.mean()

Gender                                                      1.5400
Age                                                         2.1900
Occupation                                                  1.6800
Annual Income                                               3.7200
Needle Stick Injuries                                       3.7550
Knowledge and Training on Needle Stick Injury Prevention    3.6600
Availability of Safety Equipment                            3.6575
Adherence to Safety Protocols                               3.7225
Work Environment Factors                                    3.7475
dtype: float64

In [42]:
bk.median()

Gender                                                      2.0
Age                                                         2.0
Occupation                                                  2.0
Annual Income                                               4.0
Needle Stick Injuries                                       4.0
Knowledge and Training on Needle Stick Injury Prevention    4.0
Availability of Safety Equipment                            4.0
Adherence to Safety Protocols                               4.0
Work Environment Factors                                    4.0
dtype: float64

In [2]:
def half(s):
    return 0.5*s

In [6]:
bk[['Annual Income','Occupation']].apply(half)

    Annual Income  Occupation
0             1.5         1.0
1             2.5         0.5
2             2.5         0.5
3             2.0         0.5
4             2.5         0.5
..            ...         ...
95            2.5         0.5
96            2.0         1.0
97            2.5         1.0
98            1.5         1.0
99            2.5         1.0

[100 rows x 2 columns]

In [7]:
def double(s):
    return 2*s

In [9]:
bk[['Annual Income']].apply(double)

    Annual Income
0               6
1              10
2              10
3               8
4              10
..            ...
95             10
96              8
97             10
98              6
99             10

[100 rows x 1 columns]

Done pandas library. ALHAMDULILLAH